all: myls mysearch mystat mytail

myls: myls-ElMaliki.c
	gcc -o myls myls-ElMaliki.c

mysearch: mysearch-ElMaliki.c
	gcc -o mysearch mysearch-ElMaliki.c

mystat: mystat-ElMaliki.c
	gcc -o mystat mystat-ElMaliki.c

mytail: mytail-ElMaliki.c
	gcc -o mytail mytail-ElMaliki.c 